- name: restart sshd
  systemd:
     name: sshd
     state: restarted
     enabled: yes
- name: restart chrony
  systemd:
     name: chronyd
     state: restarted
     enabled: yes
- name: restart systemd-timesyncd
  systemd:
     name: systemd-timesyncd
     state: restarted
     enabled: yes